package com.swj.ics.web_dao.domain.autodealer;

import java.math.BigDecimal;
import java.util.Date;

public class Emp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.empid
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    private Integer empid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.ename
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.hiredate
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    private Date hiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.salary
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    private BigDecimal salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.deptno
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    private Integer deptno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.empid
     *
     * @return the value of emp.empid
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    public Integer getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.empid
     *
     * @param empid the value for emp.empid
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.ename
     *
     * @return the value of emp.ename
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.ename
     *
     * @param ename the value for emp.ename
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.hiredate
     *
     * @return the value of emp.hiredate
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.hiredate
     *
     * @param hiredate the value for emp.hiredate
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.salary
     *
     * @return the value of emp.salary
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.salary
     *
     * @param salary the value for emp.salary
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.deptno
     *
     * @return the value of emp.deptno
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    public Integer getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.deptno
     *
     * @param deptno the value for emp.deptno
     *
     * @mbggenerated Thu Dec 01 19:57:11 CST 2016
     */
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }
}