package com.swj.ics.web_dao.domain.autodealer;

import java.util.Date;

public class MyBatisUser {
    public MyBatisUser()
    {

    }

    public MyBatisUser(String name)
    {
        this.user_name=name;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_user.id
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_user.user_name
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    private String user_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_user.birthday
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_user.cname
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_user.sex
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_user.sexString
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    private String sexString;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_user.mobile
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_user.email
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_user.note
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_user.id
     *
     * @return the value of mybatis_user.id
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_user.id
     *
     * @param id the value for mybatis_user.id
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_user.user_name
     *
     * @return the value of mybatis_user.user_name
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_user.user_name
     *
     * @param user_name the value for mybatis_user.user_name
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_user.birthday
     *
     * @return the value of mybatis_user.birthday
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_user.birthday
     *
     * @param birthday the value for mybatis_user.birthday
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_user.cname
     *
     * @return the value of mybatis_user.cname
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_user.cname
     *
     * @param cname the value for mybatis_user.cname
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_user.sex
     *
     * @return the value of mybatis_user.sex
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_user.sex
     *
     * @param sex the value for mybatis_user.sex
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_user.sexString
     *
     * @return the value of mybatis_user.sexString
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public String getSexString() {
        return sexString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_user.sexString
     *
     * @param sexString the value for mybatis_user.sexString
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public void setSexString(String sexString) {
        this.sexString = sexString == null ? null : sexString.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_user.mobile
     *
     * @return the value of mybatis_user.mobile
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_user.mobile
     *
     * @param mobile the value for mybatis_user.mobile
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_user.email
     *
     * @return the value of mybatis_user.email
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_user.email
     *
     * @param email the value for mybatis_user.email
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_user.note
     *
     * @return the value of mybatis_user.note
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_user.note
     *
     * @param note the value for mybatis_user.note
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}