package com.swj.ics.web_dao.inte.autodealer;

import com.swj.ics.web_dao.domain.autodealer.Emp;

public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    int deleteByPrimaryKey(Integer empid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    int insertSelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    Emp selectByPrimaryKey(Integer empid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    int updateByPrimaryKeySelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    int updateByPrimaryKey(Emp record);
}