package com.swj.ics.web_dao.inte.autodealer;

import com.swj.ics.web_dao.domain.autodealer.MyBatisUser;

public interface MyBatisUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_user
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_user
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    int insert(MyBatisUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_user
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    int insertSelective(MyBatisUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_user
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    MyBatisUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_user
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    int updateByPrimaryKeySelective(MyBatisUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_user
     *
     * @mbggenerated Sat Dec 03 21:59:20 CST 2016
     */
    int updateByPrimaryKey(MyBatisUser record);
}